---

- name: My test Playbook
  hosts: webservers
  become: true
  tasks:
   - name: stop service of httpd
     service:
       name: httpd
       state: stopped

   - name: uninstall httpd
     yum:
       name: httpd
       state: absent




