---

- name: My test playbook
  hosts: all
  become: yes
  vars_files:
    - user.yml
  
  tasks: 
    - name: ceate user using variables username= {{user1}}
      user:
        name: "{{user1}}" 
        state: absent

    - name: ceate user using variables username= {{user2}}
      user:
        name: "{{user2}}"
        state: absent

          


