
---

- name: My test playbook
  hosts: all
  become: true
  tasks:
   - name: stoping  httpd services
     service:
       name: httpd
       state: stopped
     when: ansible_os_family == "RedHat"

   - name: stoping  apache2 services
     service:
       name: apache2
       state: stopped   
     when: ansible_os_family == "Debian"

    
   - name: stop httpd
     yum:
       name: httpd
       state: absent
     when: ansible_os_family == "RedHat"

   - name: stop apache2
     apt:
       name: apache2
       state: absent
     when: ansible_os_family == "Debian"

   - name: deleting index file
     file:
       path: /var/www/html/index.html
       state: absent



